// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYsItM8p6YydI0LKNqYPG9zQnbI6RQwME',
    appId: '1:164458310170:web:20230009ff73dc6ce23fa3',
    messagingSenderId: '164458310170',
    projectId: 'tu-menu-diario-d031e',
    authDomain: 'tu-menu-diario-d031e.firebaseapp.com',
    storageBucket: 'tu-menu-diario-d031e.firebasestorage.app',
    measurementId: 'G-8EQL2M5C2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnH4Cnvuq4433OzRoDNwyOH0VE0udXRWU',
    appId: '1:164458310170:android:637cd9f85447722de23fa3',
    messagingSenderId: '164458310170',
    projectId: 'tu-menu-diario-d031e',
    storageBucket: 'tu-menu-diario-d031e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxe0yrql6ftui7x80goZQqaJLSFZLiWhw',
    appId: '1:164458310170:ios:e1806551ffe7711ce23fa3',
    messagingSenderId: '164458310170',
    projectId: 'tu-menu-diario-d031e',
    storageBucket: 'tu-menu-diario-d031e.firebasestorage.app',
    iosBundleId: 'com.example.todoAppCifo',
  );
}
